site_name: Personal Page
repo_url: https://github.com/raphael-mammeri/raphael-mammeri.github.io
repo_name:  raphael-mammeri
site_author: Raphael Mammeri
copyright: Copyright &copy; Raphael Mammeri 2023
edit_uri: edit/main/docs/
site_description: This is the site Description
extra_css:
  - stylesheets/extra.css

hooks:
    - hooks/hooks.py
theme:
  language: en
  font:
    text: Quattrocento #Niramit #Quattrocento #Aleo #Mate #Arsenal #Sawarabi
    #Mincho
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    logo: fontawesome/solid/circle-nodes
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black #blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - header.autohide
    - announce.dismiss
    - navigation.footer
    #- navigation.indexes (messes the pages numbering)
    - toc.follow
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.prune
    - navigation.instant
    - navigation.instant.progress
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/raphael-mammeri
      name: raphael-mammeri
  analytics:
    provider: google
    property: G-7PS0LETNMS


  generator: false
nav:
  - Notes:
    - Probability Theory: 
      - Introduction: notes/probability/introduction.md
      - dev: notes/probability/dev.md
      - Measure Theory: notes/probability/measure_theory.md
      - Integration: notes/probability/integration.md
      - Examples: notes/probability/examples.md
  - Articles:
      - articles/cookiecutter.md
  - Blog:
    - blog/index.md



  # - Code documentation: reference/

plugins:
  - enumerate-and-reference:
      enumerate:
        enabled: true
        cumulative: true
      number_headings:
        enabled: true
        activated: true
        lowest_level: 2

  - gen-files:
      scripts:
      - gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          paths: [../, ../src] # put here the package(s) path(s)
          options:
            show_source: false
            docstring_style: numpy
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: long
      post_url_date_format: yyyy-MM-dd
      post_url_format: "{date}-{slug}"
      categories_name: Categories
      draft: true
      draft_on_serve: true
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      fallback_to_build_date: false
      timezone: Europe/Amsterdam
      enabled: false #!ENV [CI, true]



markdown_extensions:
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/shortcuts.js