site_name: Personal Page
repo_url: https://github.com/raphael-mammeri/raphael-mammeri.github.io
repo_name:  raphael-mammeri
site_author: Raphael Mammeri
copyright: Copyright &copy; Raphael Mammeri 2023

extra_css:
  - stylesheets/extra.css


theme:
  language: en
  font:
    text: Quattrocento #Niramit #Quattrocento #Aleo #Mate #Arsenal #Sawarabi
    #Mincho
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black #blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/raphael-mammeri
      name: raphael-mammeri

  generator: false
nav:
  - Home: index.md
  - Generic: generic.md
  - Articles:
      - articles/cookiecutter.md
  - Probability Theory:
    - probability/index.md
    - Notations: probability/notations.md
    - Introduction: probability/1_Introduction.md
    - Measure Theory Basics: probability/measure_theory_basics.md
    - Integration: probability/Integral.md
    - Convergence Theorems: probability/Integral.md
    - Lp-Spaces: probability/Integral.md
    - The Probabilistic Framework: probability/Integral.md
    - Examples: probability/examples.md
    - Conditional Expectations: probability/Integral.md



  # - Code documentation: reference/

plugins:
  - gen-files:
      scripts:
      - gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          paths: [../, ../src] # put here the package(s) path(s)
          options:
            show_source: false
            docstring_style: numpy
  - enumerate-headings:
      toc_depth: 5
      strict: true
      increment_across_pages: true
      exclude:
        - index.md
      restart_increment_after:
        - probability/1_Introduction.md
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'



markdown_extensions:
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js